homeassistant:
  # Omitted values in this section will be auto detected using freegeoip.io

  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 322
  # Name of the location where Home Assistant is running
  name: Home
  # C for Celcius, F for Fahrenheit
  temperature_unit: F
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  unit_system: imperial
  customize: !include customize.yaml

zone:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  radius: 200
  icon: mdi:home

zone 2:
  name: Buckhead
  latitude: !secret latitude_buckhead
  longitude: !secret longitude_buckhead
  radius: 200
  icon: mdi:school

zone 3:
  name: Downtown
  latitude: !secret latitude_downtown
  longitude: !secret longitude_downtown
  radius: 200
  icon: mdi:school

http:
  api_password: !secret http_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret base_url
  trusted_networks:
    - 192.168.2.0/24
light:
  - platform: lifx
  # z-wave dimmer switch (http://amzn.to/2j1UEli)
  - platform: mqtt
    name: "Kitchen Lights"
    state_topic: "smartthings/Kitchen/switch"
    command_topic: "smartthings/Kitchen/switch"
    payload_on: "on"
    payload_off: "off"
    brightness_state_topic: "smartthings/Kitchen/level"
    brightness_command_topic: "smartthings/Kitchen/level"
    brightness_scale: 99
    brightness_value_template: '{{ value }}'
    retain: true
    optimistic: false
    qos: 0
#zeroconf:
recorder:
  purge_days: 3
  db_url: !secret recorder_db_url
# Enables the frontend
frontend:

# Allows you to issue voice commands from the frontend
conversation:

# Discover some devices automatically
discovery:
wemo:
updater:

#Adds Amazon Echo support
emulated_hue:
  expose_by_default: false

# Track the sun
sun:
zwave:
  usb_path: /dev/ttyACM0
  config_path: /srv/hass/hass_venv/lib/python3.4/site-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config
tts:
  - platform: google
    cache: true
    cache_dir: /home/hass/.homeassistant/tts
    time_memory: 300
  - platform: voicerss
    api_key: !secret voicerss_key

media_player:
  - platform: sonos
    hosts: 192.168.2.150
  - platform: kodi
    host: http://192.168.2.28
    port: 8080
    name: Kodi NSTV
    username: !secret kodi_username
    password: !secret kodi_password
  - platform: panasonic_viera
    host: 192.168.2.128
    port: 55000
    name: Panasonic Viera TV
  - platform: plex
    host: 192.168.2.113
  # - platform: apple_tv
  #   host: 192.168.2.90
  #   login_id: !secret apple_hsgid
camera:
  - platform: bloomsky
  - platform: generic
    still_image_url: https://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?station=FFC&brand=wui&num=1&delay=100&type=NTP&frame=0&scale=1&noclutter=0&showstorms=5&mapx=400&mapy=240&centerx=400&centery=240&transx=0&transy=0&showlabels=1&severe=0&rainsnow=0&lightning=0&smooth=0&rand=24427697&lat=0&lon=0&label=you
    name: RadarGA
  # - platform: foscam
  #   ip: 192.168.2.224
  #   name: Door Camera
  #   port: 88
  #   username: !secret foscam_username
  #   password: !secret foscam_password
  # - platform: foscam
  #   ip: 192.168.2.173
  #   name: Door Camera
  #   port: 88
  #   username: !secret foscam_username
  #   password: !secret foscam_password
  # - platform: foscam
  #   ip: 192.168.2.50
  #   name: Door Camera
  #   port: 88
  #   username: !secret foscam_username
  #   password: !secret foscam_password

ifttt:
  key: !secret ifttt_key

device_tracker:
  # - platform: asuswrt
  #   host: 192.168.2.1
  #   protocol: telnet
  #   username: !secret asus_username
  #   password: !secret asus_password
  - platform: owntracks
    max_gps_accuracy: 200
  - platform: unifi
    host: 192.168.2.163
    username: !secret unifi_username
    password: !secret unifi_password
    verify_ssl: False

notify:
  - platform: ios
  - platform: pushbullet
    api_key: !secret pushbullet_key
    name: pushbullet
  - name: telegram
    platform: telegram
    api_key: !secret telegram_key
    chat_id: !secret telegram_chatID_Alok
  - platform: ecobee
    name: ecobee

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
  username: !secret mqtt_username
  password: !secret mqtt_password

bloomsky:
  api_key: !secret bloomsky_key

ecobee:
  api_key: !secret ecobee_key
  hold_temp: True

# Log Severities: notset, debug, info, warn, warning, error, fatal, critical
logger:
  default: error
#  default: warning
#  logs:
#    homeassistant.components.notify: info
#    homeassistant.components.automation: info
#    homeassistant.components.mqtt: debug

input_select:
  abodestatus:
    name: Abode status
    options:
     - standby
     - home
     - away
    initial: standby
    icon: mdi:security
  livingroomharmony:
    name: Harmony Activity
    options:
     - PowerOff
     - Watch Fire TV
     - Chromecast
     - Youtube
     - SATV
     - Watch Apple TV
    initial: PowerOff
    icon: mdi:remote
  hdmiswitcher:
    name: HDMI Switcher
    options:
     - AppleTV
     - FireTV
     - Shield
    initial: Shield
    icon: mdi:remote
  hdmiinput:
    name: HDMI Input
    options:
     - InputHdmi1
     - InputHdmi2
     - InputHDMI3
     - InputHdmi4
    initial: InputHdmi4
    icon: mdi:remote

input_boolean:
  abodeupdate:
    name: Abode Updates
    initial: on
    icon: mdi:security
  startrecording:
    name: Camera Recording
    initial: off
    icon: mdi:record-rec
  alokhome:
    name: Alok Home
    initial: on
    icon: mdi:cellphone-iphone
  alok360home:
    name: Alok Life360
    initial: on
    icon: mdi:cellphone-iphone
  rashmihome:
    name: Rashmi Home
    initial: on
    icon: mdi:cellphone-iphone
  thermo_away_main:
    name: Downstairs Away Mode
    initial: off
    icon: mdi:home
  thermo_away_upstairs:
    name: Upstairs Away Mode
    initial: off
    icon: mdi:home
  tv:
    name: TV
    initial: off
    icon: mdi:television
  leeoalarm:
    name: Leeo Alarm
    initial: off
    icon: mdi:fire
  partymode:
    name: Party Mode
    initial: off
    icon: mdi:theme-light-dark

input_slider:
  harmonyvolume:
    icon: mdi:volume-high
    name: Volume
    initial: 30
    min: 1
    max: 100
    step: 1
  leeotemperature:
    icon: mdi:thermometer-lines
    name: Leeo Temperature
    initial: 60
    min: 20
    max: 120
    step: 0.1
  leeohumidity:
    icon: mdi:water-percent
    name: Leeo Humidity
    initial: 50
    min: 0
    max: 100
    step: 1

remote:
  - platform: harmony
    name: livingroom
    host: 192.168.2.153


# switch:
#  platform: command_line
#  switches:
#    #Switch for Foscam Motion Detection
#    foscam_record:
#      command_on: 'curl -k "http://192.168.2.173:88/cgi-bin/CGIProxy.fcgi?cmd=setMotionDetectConfig&isEnable=1&linkage=8&snapInterval=5&sensitivity=2&triggerInterval=10&isMovAlarmEnable=1&isPirAlarmEnable=1&schedule0=281474976710655&schedule1=281474976710655&schedule2=281474976710655&schedule3=281474976710655&schedule4=281474976710655&schedule5=281474976710655&schedule6=281474976710655&area0=1023&area1=1023&area2=1023=&area3=1023&area4=1023&area5=1023&area6=1023&area7=1023&area8=1023&area9=1023&usr=arsaboo&pwd=alok18"'
#      command_off: 'curl -k "http://192.168.2.173:88/cgi-bin/CGIProxy.fcgi?cmd=setMotionDetectConfig&isEnable=0&linkage=8&snapInterval=5&sensitivity=2&triggerInterval=10&isMovAlarmEnable=0&isPirAlarmEnable=0&schedule0=281474976710655&schedule1=281474976710655&schedule2=281474976710655&schedule3=281474976710655&schedule4=281474976710655&schedule5=281474976710655&schedule6=281474976710655&area0=1023&area1=1023&area2=1023=&area3=1023&area4=1023&area5=1023&area6=1023&area7=1023&area8=1023&area9=1023&usr=arsaboo&pwd=alok18"'
#      value_template: ''
#    foscam_record2:
#      command_on: 'curl -k "http://192.168.2.224:88/cgi-bin/CGIProxy.fcgi?cmd=setMotionDetectConfig&isEnable=1&linkage=8&snapInterval=5&sensitivity=2&triggerInterval=10&isMovAlarmEnable=1&isPirAlarmEnable=1&schedule0=281474976710655&schedule1=281474976710655&schedule2=281474976710655&schedule3=281474976710655&schedule4=281474976710655&schedule5=281474976710655&schedule6=281474976710655&area0=1023&area1=1023&area2=1023=&area3=1023&area4=1023&area5=1023&area6=1023&area7=1023&area8=1023&area9=1023&usr=arsaboo&pwd=alok18"'
#      command_off: 'curl -k "http://192.168.2.224:88/cgi-bin/CGIProxy.fcgi?cmd=setMotionDetectConfig&isEnable=0&linkage=8&snapInterval=5&sensitivity=2&triggerInterval=10&isMovAlarmEnable=0&isPirAlarmEnable=0&schedule0=281474976710655&schedule1=281474976710655&schedule2=281474976710655&schedule3=281474976710655&schedule4=281474976710655&schedule5=281474976710655&schedule6=281474976710655&area0=1023&area1=1023&area2=1023=&area3=1023&area4=1023&area5=1023&area6=1023&area7=1023&area8=1023&area9=1023&usr=arsaboo&pwd=alok18"'
#      value_template: ''
#    foscam_record3:
#      command_on: 'curl -k "http://192.168.2.50:88/cgi-bin/CGIProxy.fcgi?cmd=setMotionDetectConfig&isEnable=1&linkage=8&snapInterval=5&sensitivity=2&triggerInterval=10&isMovAlarmEnable=1&isPirAlarmEnable=1&schedule0=281474976710655&schedule1=281474976710655&schedule2=281474976710655&schedule3=281474976710655&schedule4=281474976710655&schedule5=281474976710655&schedule6=281474976710655&area0=1023&area1=1023&area2=1023=&area3=1023&area4=1023&area5=1023&area6=1023&area7=1023&area8=1023&area9=1023&usr=arsaboo&pwd=alok18"'
#      command_off: 'curl -k "http://192.168.2.50:88/cgi-bin/CGIProxy.fcgi?cmd=setMotionDetectConfig&isEnable=0&linkage=8&snapInterval=5&sensitivity=2&triggerInterval=10&isMovAlarmEnable=0&isPirAlarmEnable=0&schedule0=281474976710655&schedule1=281474976710655&schedule2=281474976710655&schedule3=281474976710655&schedule4=281474976710655&schedule5=281474976710655&schedule6=281474976710655&area0=1023&area1=1023&area2=1023=&area3=1023&area4=1023&area5=1023&area6=1023&area7=1023&area8=1023&area9=1023&usr=arsaboo&pwd=alok18"'
#      value_template: ''

ios:

# View all events in a logbook
logbook:
  exclude:
    domains:
      - sun
      - automation
    entities:
      - sensor.pws_weather
      - sensor.pws_temp_f
      - sensor.pws_pressure_in
      - sensor.pws_relative_humidity
      - binary_sensor.ars_bloom_rain
      - binary_sensor.ars_bloom_night
      - binary_sensor.garage_door_tilt_sensor_sensor_5_0
      - sensor.ars_bloom_uvindex
      - sensor.pws_wind_dir
      - sensor.pws_wind_string
      - sensor.dark_sky_cloud_coverage
      - sensor.dark_sky_hourly_summary
      - sensor.dark_sky_wind_speed
      - sensor.dark_sky_daily_summary
      - sensor.time__date
      - sensor.bloomlastupdate
      - sensor.garage_door_tilt_sensor_alarm_level_5_1
      - sensor.garage_door_tilt_sensor_alarm_type_5_0
      - sensor.garage_door_tilt_sensor_burglar_5_10
      - sensor.garage_door_tilt_sensor_sourcenodeid_5_2
      - sensor.garagedoorbattery
      - sensor.phonebatteryalok
      - sensor.phonebatteryrashmi
      - sensor.usd_inr
      - sensor.usd_eur
      - sensor.sonos_volume
      - sensor.downstairsthermoper
      - sensor.upstairsthermostatoperation
      - group.abode_status
      - group.device_location
      - group.information
      - group.thermostats
      - group.media_player
      - group.weather
      - group.devices
      - group.all_lights
      - group.household
      - group.entertainment
      - device_tracker.unificloudkey
      - media_player.unnamed_device
      - media_player.livingroomsonos
      - media_player.plex_web_chrome_2
      - media_player.plex_web_chrome
      - automation.update_volume_slider
      - automation.heal_zwave_network
      - automation.set_volume
      - automation.turn_tv_onoff
      - automation.start_harmony_activity_from_input_select
      - automation.update_ha_if_harmony_activity_changes
      - automation.update_tv_status_in_ha
      - input_slider.harmonyvolume
      - input_slider.leeotemperature
      - input_slider.leeohumidity
      - input_boolean.leeoalarm
# Enables support for tracking state changes over time.
history:
  include:
    entities:
      - binary_sensor.garagedoor
      - device_tracker.alokiosiphone
      - device_tracker.myiphone
      - device_tracker.pi_alokphone
      - device_tracker.pi_rashmiphone
      - device_tracker.rashmiappiphone
      - device_tracker.rashmisiphone
      - input_boolean.alokhome
      - input_boolean.rashmihome
      - input_select.abodestatus
      - media_player.panasonic_viera_tv
      - sensor.ars_bloom_temperature
      - sensor.evening_commute
      - sensor.morning_commute
      - sensor.plexspy
      - switch.driveway
automation: !include automation.yaml
group: !include groups.yaml
script: !include scripts.yaml
sensor: !include sensor.yaml
binary_sensor: !include binary_sensor.yaml
alexa: !include alexa.yaml
apiai: !include apiai.yaml
