homeassistant:
  customize:
     input_boolean.abodeupdate:
       emulated_hue: true
input_select:
  abodestatus:
    name: Abode status
    options:
     - standby
     - home
     - away
    initial: standby
    icon: mdi:security
input_boolean:
  abodeupdate:
    name: Abode Updates
    initial: on
    icon: mdi:security

automation:
- alias: 'Disarm Abode from Away'
  initial_state: 'on'
  condition:
    condition: state
    entity_id: input_select.abodestatus
    state: 'away'
  trigger:
   - platform: state
     entity_id: group.household
     state: 'on'
  action:
     service: homeassistant.turn_on
     entity_id: script.abodestandby

- alias: 'Garage Door open'
  initial_state: 'on'
  condition:
    condition: state
    entity_id: sensor.garagedoor
    state: 'Open'
  trigger:
    - platform: state
      entity_id: input_select.abodestatus
      state: 'home'
    - platform: state
      entity_id: input_select.abodestatus
      state: 'away'
  action:
    - service: notify.pushbullet
      data:
        message: "Garage Door Open"
        title: "Garage Door Open"
    - service: homeassistant.turn_on
      entity_id: script.notificationgaragedoor

- alias: 'Disarm Abode at night'
  initial_state: 'on'
  condition:
    condition: state
    entity_id: input_select.abodestatus
    state: 'home'
  trigger:
   - platform: state
     entity_id: input_boolean.rashmihome, input_boolean.alokhome
     to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: script.abodestandby

- alias: 'Abode Home from Standby'
  initial_state: 'on'
  condition:
    condition: and
    conditions:
     - condition: state
       entity_id: input_select.abodestatus
       state: 'standby'
     - condition: time
       after: '22:15:00'
       before: '07:30:00'
     - condition: state
       entity_id: input_boolean.abodeupdate
       state: 'on'
     - condition: template
       value_template: >
         {%- if states.input_select.abodestatus.last_changed -%}
           {{ (as_timestamp(now()) - as_timestamp(states.input_select.abodestatus.last_changed)) > 300 }}
         {%- else -%}
           true
         {%- endif -%}
  trigger:
   - platform: time
     minutes: '/10'
     seconds: 00
  action:
     service: homeassistant.turn_on
     entity_id: script.abodehome

- alias: 'Abode Standby'
  initial_state: 'on'
  condition:
    condition: and
    conditions:
     - condition: state
       entity_id: group.household
       state: 'on'
     - condition: time
       after: '08:15:00'
       before: '21:45:00'
     - condition: state
       entity_id: input_boolean.abodeupdate
       state: 'on'
     - condition: template
       value_template: >
         {%- if states.input_select.abodestatus.last_changed -%}
           {{ (as_timestamp(now()) - as_timestamp(states.input_select.abodestatus.last_changed)) > 300 }}
         {%- else -%}
           true
         {%- endif -%}
     - condition: or
       conditions:
        - condition: state
          entity_id: input_select.abodestatus
          state: 'home'
        - condition: state
          entity_id: input_select.abodestatus
          state: 'away'
  trigger:
   - platform: time
     minutes: '/10'
     seconds: 00
  action:
     service: homeassistant.turn_on
     entity_id: script.abodestandby

- alias: 'Adjust settings changed by Abode'
  initial_state: 'on'
  condition:
    condition: and
    conditions:
     - condition: or
       conditions:
        - condition: state
          entity_id: input_select.abodestatus
          state: 'home'
        - condition: state
          entity_id: input_select.abodestatus
          state: 'standby'
     - condition: or
       conditions:
        - condition: state
          entity_id: input_boolean.thermo_away_main
          state: 'on'
        - condition: state
          entity_id: input_boolean.thermo_away_upstairs
          state: 'on'
  trigger:
   - platform: time
     minutes: '/10'
     seconds: 00
  action:
     - service: climate.set_away_mode
       data:
         entity_id: climate.downstairs
         away_mode: 'False'
     - service: climate.set_away_mode
       data:
         entity_id: climate.upstairs
         away_mode: 'False'

- alias: 'Arm Abode'
  initial_state: 'on'
  condition:
    condition: state
    entity_id: input_boolean.abodeupdate
    state: 'on'
  trigger:
    - platform: state
      entity_id: group.household
      state: 'off'
  action:
     service: homeassistant.turn_on
     entity_id: script.abodeaway

- alias: 'Abode Home at night'
  initial_state: 'on'
  condition:
    condition: and
    conditions:
     - condition: state
       entity_id: input_boolean.abodeupdate
       state: 'on'
     - condition: state
       entity_id: group.household
       state: 'on'
  trigger:
    platform: time
    after: '22:00:00'
  action:
     service: homeassistant.turn_on
     entity_id: script.abodehome

- alias: 'Disarm Abode in the morning'
  initial_state: 'on'
  condition:
    condition: and
    conditions:
     - condition: state
       entity_id: group.household
       state: 'on'
     - condition: state
       entity_id: input_boolean.abodeupdate
       state: 'on'
  trigger:
    platform: time
    after: '07:45:00'
  action:
     service: homeassistant.turn_on
     entity_id: script.abodestandby
