homeassistant:
  customize:
     switch.driveway:
       emulated_hue: true
       emulated_hue_name: "Driveway Light"
       friendly_name: "Driveway Light"
light:
  - platform: lifx
  # z-wave dimmer switch (http://amzn.to/2j1UEli)
  - platform: mqtt
    name: "Kitchen Lights"
    state_topic: "smartthings/Kitchen/switch"
    command_topic: "smartthings/Kitchen/switch"
    payload_on: "on"
    payload_off: "off"
    brightness_state_topic: "smartthings/Kitchen/level"
    brightness_command_topic: "smartthings/Kitchen/level"
    brightness_scale: 99
    brightness_value_template: '{{ value }}'
    retain: true
    optimistic: false
    qos: 0

input_boolean:
  partymode:
    name: Party Mode
    initial: off
    icon: mdi:theme-light-dark

automation:
- alias: 'Kitchen light brightness'
  initial_state: 'on'
  trigger:
   - platform: state
     entity_id: light.kitchen_lights
     state: 'on'
  action:
     service: light.turn_on
     data:
       entity_id: light.kitchen_lights
       brightness: 240

- alias: 'Change Leeo color'
  initial_state: 'on'
  condition:
    - condition: state
      entity_id: device_tracker.leeoalert
      state: 'home'
    - condition: time
      after: '19:15:00'
      before: '07:45:00'
    - condition: state
      entity_id: binary_sensor.living_room_occupancy
      state: 'on'
  trigger:
   - platform: time
     minutes: '/15'
     seconds: 00
  action:
     service: ifttt.trigger
     data_template: {"event":"leeocolor", "value1":"{{ '{:02x}{:02x}{:02x}'.format(range(0, 255) | random, range(0, 255) | random, range(0, 255) | random) }}"}

- alias: 'Change Leeo upstairs color'
  initial_state: 'on'
  condition:
    - condition: time
      after: '19:15:00'
      before: '07:45:00'
  trigger:
   - platform: time
     minutes: '/15'
     seconds: 00
  action:
     service: ifttt.trigger
     data_template: {"event":"leeocolorup", "value1":"{{ '{:02x}{:02x}{:02x}'.format(range(0, 255) | random, range(0, 255) | random, range(0, 255) | random) }}"}

- alias: "Turn Lifx Party Mode On"
  initial_state: 'on'
  trigger:
    - platform: time
      seconds: '/3'
  condition:
    - condition: state
      entity_id: input_boolean.partymode
      state: 'on'
  action:
    - service: light.turn_on
      entity_id: light.lifxnrkitchen
      data_template:
        rgb_color: ['{{ (range(0, 255)|random) }}', '{{ (range(0, 255)|random) }}', '{{ (range(0, 255)|random) }}']
        brightness: 220
        transition: '{{ (range(1, 2)|random) }}'
    - service: light.turn_on
      entity_id: light.lifxnrguest
      data_template:
        rgb_color: ['{{ (range(0, 255)|random) }}', '{{ (range(0, 255)|random) }}', '{{ (range(0, 255)|random) }}']
        brightness: 220
        transition: '{{ (range(1, 2)|random) }}'
    - service: light.turn_on
      entity_id: light.lifx3
      data_template:
        rgb_color: ['{{ (range(0, 255)|random) }}', '{{ (range(0, 255)|random) }}', '{{ (range(0, 255)|random) }}']
        brightness: 220
        transition: '{{ (range(1, 2)|random) }}'
- alias: "Turn Lifx Party Mode Off"
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.partymode
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: group.living_room_lights
      data:
        rgb_color: [255, 255, 255]
        brightness: 250
        color_temp: 285

- alias: Driveway light at night
  initial_state: 'on'
  trigger:
    platform: sun
    event: sunset
    offset: "00:45:00"
  action:
    - service: switch.turn_on
      entity_id: switch.driveway

- alias: Driveway light Off
  initial_state: 'on'
  trigger:
    platform: sun
    event: sunset
    offset: "01:30:00"
  action:
    - service: switch.turn_off
      entity_id: switch.driveway
- alias: Driveway light Off during the day
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: switch.driveway
    state: 'on'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'above_horizon'
  action:
    - service: switch.turn_off
      entity_id: switch.driveway

- alias: Turn lights on randomly
  initial_state: 'on'
  condition:
    condition: state
    entity_id: input_select.abodestatus
    state: 'away'
  trigger:
    platform: sun
    event: sunset
    offset: "00:45:00"
  action:
    - service: light.turn_on
      data:
        entity_id: group.living_room_lights

- alias: Turn off lights 2 hours
  initial_state: 'on'
  condition:
    - condition: state
      entity_id: input_select.abodestatus
      state: 'away'
    - condition: state
      entity_id: group.living_room_lights
      state: 'on'
  trigger:
    platform: sun
    event: sunset
    offset: "02:45:00"
  action:
    - service: light.turn_off
      data:
        entity_id: group.living_room_lights

script:
  colorloop_start:
    alias: 'Start LIFX colorloop'
    sequence:
      - service: light.lifx_effect_colorloop
        data:
          entity_id: group.living_room_lights
          brightness: 255
          period: 10
          spread: 35
          change: 35

  disco_party:
    alias: 'Start Party Mode'
    sequence:
      - service: light.lifx_effect_colorloop
        data:
          entity_id: group.living_room_lights
          brightness: 255
          period: 1
          spread: 359
          change: 35

  lifx_stop_effects:
    alias: 'Stop LIFX effects'
    sequence:
      - service: light.lifx_effect_stop
        data:
          entity_id: group.all_lights
      - service: light.turn_on
        entity_id: group.living_room_lights
        data:
          rgb_color: [255, 255, 255]
          brightness: 250
          color_temp: 285
